--- #YAML:1.0
name:                Data-ResultSet
version:             1.002
abstract:            Container for aggregating and examining multiple results
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Dianne Skoll <dianne@skoll.ca>
    - Dave O'Neill <dmo@dmo.ca>
